### ISSUE TITLE
Footnotes on the main blog page

### ISSUE THREAD

**Issue by Hunter-Github** [celsomiranda/hexo-renderer-markdown-it#13]
Suppose we have 3 blog entries (e1-e3), each with 3 footnotes (f11, f12 ... f33). Currently, footnotes f21...f23 map to f11...f13 and similarly for f31...f33, when the main blog page is displayed. Not a big deal, but readers may be a bit confused.

Ideally, one would prepend the slug to footnote number to avoid ambiguity: 
`#entry1-fn1`.

**Comment by celsomiranda** [comment]
I'm sorry. I couldn't understand. Can you explain it in another way?

**Comment by Hunter-Github** [comment]
Maybe this is a misplaced bugrep which should go to hexojs/hexo instead.

A blog is composed of several entries. When I add footnotes to an entry, the anchors are numbered `#fn1`, `#fn2` etc. Hexo joins the entries in a single page but does not change the anchors. Thus, when I click on the 2nd footnote of an entry other than the top one, the browser navigates to the topmost (and hence, wrong) `#fn2` anchor.

I see two solutions:

* fix hexo's algorithm
* fix footnote anchor names in the renderer

**Comment by celsomiranda** [comment]
One way to test if this is related with this renderer is to see if the
problem persists with `hexo-renderer-marked`.

AFAIK this plugin doesn't have that functionality since it only parses the
markdown inside a file, and does not correlate the content between multiple
files.

2015-05-28 18:38 GMT+01:00 Hunter-Github <notifications@github.com>:

**Comment by Hunter-Github** [comment]
Will raise it in the main hexo repo.
